runtime: php74

runtime_config:
  document_root: ./public

includes:
- .gcp/env.yaml

handlers:
  - url: /css
    static_dir: public/css

  - url: /js
    static_dir: public/js

  - url: .*
    script: auto
