runtime: php74

vpc_access_connector:
  name: projects/toei-portal-admin-development/locations/asia-northeast1/connectors/connector01
  egress_setting: all-traffic

runtime_config:
  document_root: ./public

includes:
- .gcp/env.yaml

env_variables:
  APPSETTING_VIEW_CACHE_DIR: /tmp/view

handlers:
  - url: /css
    static_dir: public/css

  - url: /js
    static_dir: public/js

  - url: .*
    script: auto
