version: '3'

services:
  web:
    build: ./docker/web
    ports:
      - "8000:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mopix
      TZ: Asia/Tokyo
    volumes:
      # - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf # Dockerfileで対応
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mopix
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
