# CircleCI configuration

version: 2.1

# YAML記法を使った参照（CircleCIの設定ではない）
# https://circleci.com/docs/ja/2.0/writing-yaml/#%E3%82%A2%E3%83%B3%E3%82%AB%E3%83%BC%E3%81%A8%E3%82%A8%E3%82%A4%E3%83%AA%E3%82%A2%E3%82%B9
references:

  # https://circleci.com/docs/ja/2.0/private-images/
  docker_hub_authentication: &docker_hub_authentication
    auth:
      username: $DOCKERHUB_ID
      password: $DOCKERHUB_ACCESS_TOKEN

  job_setup: &job_setup
    context: docker-hub-creds

commands:
  fix_composer_version:
    description: "Composerのバージョンを固定"
    steps:
      - run:
          name: Using Composer version 2
          command: sudo composer self-update --2

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

executors:
  build:
    docker:
      - image: cimg/php:7.4
        <<: *docker_hub_authentication

jobs:
  test:
    working_directory: ~/test
    executor: build

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-dev-{{ checksum "composer.lock" }}
            - composer-

      - fix_composer_version

      - run:
          name: Composer install (with require-dev)
          command: composer install -n --prefer-dist

      - save_cache:
          key: composer-dev-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Create .env file
          command: cp .env.test .env

      - run:
          name: PHP Lint
          command: composer phplint

      - run:
          name: PHP CodeSniffer
          command: composer phpcs

      - run:
          name: PHPStan
          command: composer phpstan > ./report/phpstan_result.txt

      - run:
          name: PHPUnit
          command: composer phpunit

      - store_artifacts:
          path: ./report

      - run:
          name: Remove .env file
          command: rm -v ./.env

  deploy_to_development:
    working_directory: ~/deployment-dev
    executor: gcp-cli/default

    steps:
      - checkout

      - run:
          name: Create app.yaml
          command: sed s/:PROJECT_ID:/$GOOGLE_PROJECT_ID_DEVELOPMENT/ ./.gcp/app.yaml > app.yaml

      - store_artifacts:
          path: ./app.yaml

      - run:
          name: Copy php.ini
          command: cp ./.gcp/php.development.ini php.ini

      - run:
          name: Create includes env yaml
          command: echo $ENV_VARIABLES_DEVELOPMENT | base64 --decode > ./.gcp/env.yaml

      - store_artifacts:
          path: ./.gcp/env.yaml

      - gcp-cli/install

      - gcp-cli/initialize:
          gcloud-service-key: GCLOUD_SERVICE_KEY_DEVELOPMENT
          google-compute-region: GOOGLE_COMPUTE_REGION_DEVELOPMENT
          google-project-id: GOOGLE_PROJECT_ID_DEVELOPMENT

      # composerのコマンドイベントを使いたいのでキャッシュを無効にする
      - run: gcloud --quiet app deploy --no-cache

  deploy_to_production:
    working_directory: ~/deployment-prod
    executor: gcp-cli/default
    steps:
      - checkout

      - run:
          name: Create app.yaml
          command: sed s/:PROJECT_ID:/$GOOGLE_PROJECT_ID_PRODUCTION/ ./.gcp/app.yaml > app.yaml

      - store_artifacts:
          path: ./app.yaml

      - run:
          name: Copy php.ini
          command: cp ./.gcp/php.production.ini php.ini

      - run:
          name: Create includes env yaml
          command: echo $ENV_VARIABLES_PRODUCTION | base64 --decode > ./.gcp/env.yaml

      - store_artifacts:
          path: ./.gcp/env.yaml

      - gcp-cli/install

      - gcp-cli/initialize:
          gcloud-service-key: GCLOUD_SERVICE_KEY_PRODUCTION
          google-compute-region: GOOGLE_COMPUTE_REGION_PRODUCTION
          google-project-id: GOOGLE_PROJECT_ID_PRODUCTION

      # composerのコマンドイベントを使いたいのでキャッシュを無効にする
      - run: gcloud --quiet app deploy --no-cache

workflows:
  version: 2

  deploy_development:
    jobs:
      - test:
          <<: *job_setup
          filters:
            branches:
              only: feature/TOEI-382

      - deploy_to_development:
          <<: *job_setup
          filters:
            branches:
              only: feature/TOEI-382

      - deploy_to_production:
          <<: *job_setup
          requires:
            - test
