name: Development

on:
  push:
    branches-ignore:
     - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Directory
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install (with dev)
        run: composer install --prefer-dist --no-progress --no-suggest

      - uses: actions/upload-artifact@v1
        with:
          name: application
          path: .

  test:
    name: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo Test

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploy
